import saber
import time

print("forward")
saber.forward()
time.sleep(2)
print("backward")
saber.backward()
time.sleep(2)
print("left")
saber.left()
time.sleep(1)
print("hardleft")
saber.hardLeft()
time.sleep(1)
print("right")
saber.right()
time.sleep(1)
print("hardright")
saber.hardRight()
time.sleep(1)
saber.stopforwardback()
print("up")
saber.up()
time.sleep(2)
print("down")
saber.down()
time.sleep(2)
print("stop")
saber.stop()